# -*- coding: utf-8 -*-
"""ProjetPythonVendredi10/07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BVGTJgFmjaDCkaUqnLQFyweTLsA0-AQ2

Import des bibliothèques
"""

#https://ledatascientist.com/
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
print("Importé")

"""Connexion avec le Google Drive"""

from google.colab import drive
drive.mount('/content/gdrive')

"""Intégration du fichier voulu dans "df""""

df=pd.read_csv('/content/gdrive/My Drive/Python/Data/datasets_723010_1257097_fatal-police-shootings-data.csv')
#df_filtre = df [ df ["armed"] != "knife"]
#df_filtre = df_filtre [ df_filtre ["armed"] != "gun"]
nombre_WA = np.sum(df.state=="RI")
nombre_WA

"""Analyse du DATASET :

Concernant les types de données, on a des "objet" en majorité, une variable "bool" et un float.
Ce DATASET dispose de colonnes indiquant des noms, des manières de mourrir, quel arme cette personne avait, son sexe, la ville etc ...
On en déduit très simplement, en regardant en plus le nom du fichier, que ce fichier répertorie les informations des personnes décédées lors d'intervention de police.

Il y a 14 colonnes différentes ce qui nous laisse beaucoup de choix et d'idées à exploiter.

Le premier graphique auquel on peut penser, c'est évidemment la quantité de mort en fonction de l'origine ethnique de la victime et de son sexe.
D'autres graphiques viennent ensuite en tête : 
*   Tendance du nombre de morts en fonction des états
*   Tendance de l'age des morts
*   Nombre de morts par période

Graphiques :
"""

x= df.age
sns.distplot(x)

"""Ce graphique met en évidence la tendance de l'age  des personnes mourant lors des interventions de police : ~~30 ans"""

armed_gun = np.sum(df.armed=="gun")
armed_knife = np.sum(df.armed=="knife")
armed_unarmed = np.sum(df.armed=="unarmed")
armed_others = sum(1 for _ in df.armed)
armed_others = armed_others - armed_knife - armed_gun - armed_unarmed

sizes = [armed_others, armed_gun, armed_knife, armed_unarmed]
labels = 'Others', 'Gun', 'Knife', 'Unarmed'
x = plt.pie(sizes, labels=labels, autopct='%1.1f%%', shadow=True, startangle=90)

"""Ce diagramme circulaire met en évidence les armes qui ont été utilisées par la victime de l'intervention"""

"""
#plt.scatter(df.date, df.date)
#x= df.date.count(df.date)
#sns.distplot(x)
pd.to_datetime(df.date)
df.groupby(df.date)
"""
"""
df["date"] = df["date"].astype("datetime64")
df2 = df.date
df.date.groupby(df["date"]).count().plot(kind="bar")
"""
fig, ax = plt.subplots()
df["date"].astype(np.int64).plot.hist(ax=ax)
labels = ax.get_xticks().tolist()
labels = pd.to_datetime(labels)
ax.set_xticklabels(labels, rotation=90)
plt.show()

"""Diagramme visant à obtenir un aperçu sur les periodes avec le plus de morts (pas encore finis)."""

plt.figure(1, figsize=(20, 5))
x = plt.hist(df.state,edgecolor = 'red', bins=51)

"""Ce grahique met en évidence le nombre de mort en fonction des états. On peut ainsi voir que certains états ont un nombre de mort par intervention de police extremement élevé !"""

race_W = np.sum(df.race=="W")
race_B = np.sum(df.race=="B")
race_H = np.sum(df.race=="H")
race_A = np.sum(df.race=="A")
race_N = np.sum(df.race=="N")
race_O = np.sum(df.race=="O")

df_CA = df [ df["state"] == "CA"]
df_CA

