# -*- coding: utf-8 -*-
"""ProjetPythonVendredi10/07-Rendu_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BVGTJgFmjaDCkaUqnLQFyweTLsA0-AQ2

Import des bibliothèques
"""

#https://ledatascientist.com/
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
print("Importé")

"""Connexion avec le Google Drive"""

from google.colab import drive
drive.mount('/content/gdrive')

"""Intégration du fichier voulu dans le DataFrame : "df""""

df=pd.read_csv('/content/gdrive/My Drive/Python/Data/datasets_723010_1257097_fatal-police-shootings-data.csv')
df = df.fillna(0)

df

"""Analyse du DATASET :

Concernant les types de données, on a des "objet" en majorité, une variable "bool" et un float.
Ce DATASET dispose de colonnes indiquant des noms, des manières de mourrir, quel arme cette personne avait, son sexe, la ville etc ...
On en déduit très simplement, en regardant en plus le nom du fichier, que ce fichier répertorie les informations des personnes décédées lors d'intervention de police.

Il y a 14 colonnes différentes ce qui nous laisse beaucoup de choix et d'idées à exploiter.


En voyant ces différentes colonnes et son contenu, on peut penser à plusieurs graphiques : 
*   Nombres de morts par états
*   Race les plus touchés dans un état
*   Armes les plus utilisés
*   Tendance de l'age des morts
*   Nombre de morts en fonction des mois
*   Nombre de femmes tuées comparé au nombre d'hommes tués et ce, en prennant compte des troubles mentaux

Graphiques :
"""

df1 = df [ df ["age"] > 0]
x= df1["age"]
e = sns.distplot(x)
e = plt.title("Tendance d'age des morts")

"""Ce graphique met en évidence la tendance de l'age  des personnes mourant lors des interventions de police : très peu de personnes en dessous  de 18 ans, une grande masse de gens vers les 30 ans et tout de même quelques personnes agées."""

#Cette première partie de code devrait avoir sa méthode qui simplifie cette import afin d'automatiser à 100% les infos. En attendant, cette manière de faire fonctionne aussi
armed_gun = np.sum(df.armed=="gun")
armed_knife = np.sum(df.armed=="knife")
armed_unarmed = np.sum(df.armed=="unarmed")
armed_others = sum(1 for _ in df.armed) - np.sum(df.armed==0)
armed_others = armed_others - armed_knife - armed_gun - armed_unarmed

sizes = [armed_others, armed_gun, armed_knife, armed_unarmed]
labels = 'Autre', 'Pistolet', 'Couteau', 'Non armé'
x = plt.pie(sizes, labels=labels, autopct='%1.1f%%', shadow=True, startangle=90)
x =plt.title("Arme les plus utilisées par les victimes des interventions")

"""Ce diagramme circulaire met en évidence les armes qui ont été utilisées par la victime de l'intervention. L'on peut donc voir que le pistolet est l'arme la plus utilisée par les victimes des interventions policières."""

df2 = df.date [ df["date"].dt.year == 2019]
plt.title("Classement par mois du nombre de morts lors de l'année 2019")
#plt.xticks(rotation = 'vertical')
axes = plt.gca()

x = df2.groupby(df2.dt.month).count().plot(kind="bar")
x = axes.xaxis.set_ticklabels(["01/19","02/19","03/19","04/19","05/19","06/19","07/19","08/19","09/19","10/19","11/19","12/19"], 
                          rotation = 0, color = 'black', fontsize = 8, verticalalignment = 'center')

"""Diagramme visant à obtenir un aperçu sur les periodes avec le plus de morts. On constate donc que les interventions en Décembre sont les plus meurtrières, suivi par Janvier."""

plt.figure(1, figsize=(20, 5))
x = plt.hist(df.state,edgecolor = 'red', bins=51)
x = plt.title("Nombre de morts en fonction des états des USA")

"""Ce grahique nous montre le nombre de mort en fonction des états. On peut ainsi voir que certains états ont un nombre de mort par intervention de police extremement élevé comme la Californie (CA), suivie par le  Texas (TX) et par la Floride (FL)."""

df_CA = df [ df["state"] == "CA"]
race_W = np.sum(df_CA.race=="W")
race_B = np.sum(df_CA.race=="B")
race_H = np.sum(df_CA.race=="H")
race_A = np.sum(df_CA.race=="A")
race_N = np.sum(df_CA.race=="N")
race_O = np.sum(df_CA.race=="O")
#print("White : {} \nBlack : {} \nHispannic : {} \nAsian : {} \nNative : {} \nOther : {}".format(race_W, race_B, race_H, race_A, race_N, race_O))

labels = ['Blanc', 'Noir', 'Americain Natif', 'Asiatique', 'Hispanique', 'Autre']
values = race_W, race_B, race_N, race_A,  race_H , race_O
num_vars = len(labels)
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
values += values[:1]
angles += angles[:1]

fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))

ax.plot(angles, values, color='red', linewidth=1)
ax.fill(angles, values, color='red', alpha=0.25)
ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
plt.title(" Classsification ethnique des morts en Californie")
x = ax.set_thetagrids(np.degrees(angles), labels)

"""Ce graphique met en évidence les catégories ethniques les plus "visées" par les intervention de police meurtrière. On y voit donc que la communauté la plus touché par ces morts est la communauté hispannique suivie par celle des blancs puis des noirs. Néanmoins, avant de faire une conclusion, il serait intéressant d'avoir des informations sur les quantités de types de populations en Californie."""

df1 = df[df["gender"] != 0]

df2_M = df1[df1["gender"] == "M"]
df2_F = df1[df1["gender"] == "F"]

illness_M = df2_M[df2_M["signs_of_mental_illness"] == True]
illness_F = df2_F[df2_F["signs_of_mental_illness"] == True]
illness_M = np.sum(illness_M["signs_of_mental_illness"]== True)
illness_F = np.sum(illness_F["signs_of_mental_illness"]== True)

df1 = df1.gender

gender_F = np.sum(df1=="F")
gender_M = np.sum(df1=="M")
gender_M += - illness_M
gender_F += - illness_F

x = plt.bar(1, height=gender_M, color = "cyan", edgecolor = "green")
x = plt.bar(1, height=illness_M, color = "yellow", edgecolor = "red")
x = plt.bar(2, height=gender_F, color = "cyan", edgecolor = "green")
x = plt.bar(2, height=illness_F, color = "yellow", edgecolor = "red")
x = plt.xticks(range(3),[0, "Male", "Female"])
x = plt.title("Comparaison entre le nombre d'homme et le nombre de femme tuées\nEn jaune figure le nombre présentant des troubles psychiatriques")

"""Ce diagramme permet de mettre en avant la faible quantité de femme tuée lors des interventions de police. Les hommes sont donc largement majoritaires en ce qui concerne leurs morts.
Il nous est aussi montré en jaune la quantité de personne ayant présenté des "signes de maladies mentales" et nous éclaire donc sur la part de personne saine d'esprit tuée.
"""